package org.xiaoyu.gitarena.domain.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.time.OffsetDateTime;

/**
 * 用户实体（database.md §3.1，落库到 users 表）。含游客（is_guest）。
 *
 * <p>省略 public_id / oauth_* / total_points 默认等由 DB 默认值接管的列——插入时不带这些字段，
 * DB 的 DEFAULT（gen_random_uuid()、now()、0、false…）生效；主键 GENERATED BY DEFAULT AS IDENTITY
 * 配合 MyBatis-Plus IdType.AUTO 回读。
 */
@Data
@TableName("users")
public class User {

    @TableId(type = IdType.AUTO)
    private Long id;

    private String username;
    private String email;
    private String passwordHash;
    private String displayName;
    private Boolean isGuest;
    private String avatarColor;
    private Integer totalPoints;
    private String status;
    /** 仅游客：created_at + 24h。正式用户为 null。 */
    private OffsetDateTime expiresAt;
    // 库列为 timestamptz（database.md §0）：须用 OffsetDateTime，pgjdbc 拒绝把 timestamptz 读进 LocalDateTime。
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
}
